document.addEventListener("DOMContentLoaded", function () {
    new Typed("#typewriter", {
        strings: ["Network geek", "Coding Jedi", "Life time learner", "Computer Scientist", "Keyboard stroker",
            "Coder with a soul",
            "Watchman of the matrix",
            "Digital alchemist",
            "Bug hunter",
            "Script ninja",
            "Code whisperer",
            "Syntax magician",
            "Pixel pusher",
            "Debugging demon",
            "Data wrangler",
            "Cyber warrior",
            "Keeper of keys",
            "Packet sorcerer",
            "Bit bender",
            "Algorithm artist",
            "Guardian of the Galaxy",
            "Binary bard",
            "Crypto crusader",
            "Network guardian",
            "Server sage",
            "Guardian of code",
            "Architect of data",
            "Master of servers"],
        typeSpeed: 60,
        backSpeed: 50,
        backDelay: 1500,
        startDelay: 500,
        loop: true,
        showCursor: true,
        cursorChar: '_',
        smartBackspace: true,
    });
});